package Server;


/**
* Server/TaxesPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Taxes.idl
* Sunday, April 26, 2020 4:23:58 PM EDT
*/

public abstract class TaxesPOA extends org.omg.PortableServer.Servant
 implements Server.TaxesOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("calculateTax", new java.lang.Integer (0));
    _methods.put ("shutdown", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Server/Taxes/calculateTax
       {
         double salary = in.read_double ();
         double taxRate = in.read_double ();
         String $result = null;
         $result = this.calculateTax (salary, taxRate);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // Server/Taxes/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Server/Taxes:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Taxes _this() 
  {
    return TaxesHelper.narrow(
    super._this_object());
  }

  public Taxes _this(org.omg.CORBA.ORB orb) 
  {
    return TaxesHelper.narrow(
    super._this_object(orb));
  }


} // class TaxesPOA
