package Server;

/**
* Server/TaxesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Taxes.idl
* Sunday, April 26, 2020 4:23:58 PM EDT
*/

public final class TaxesHolder implements org.omg.CORBA.portable.Streamable
{
  public Server.Taxes value = null;

  public TaxesHolder ()
  {
  }

  public TaxesHolder (Server.Taxes initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server.TaxesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server.TaxesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server.TaxesHelper.type ();
  }

}
