package Server;


/**
* Server/TaxesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Taxes.idl
* Sunday, April 26, 2020 4:23:58 PM EDT
*/

public interface TaxesOperations 
{
  String calculateTax (double salary, double taxRate);
  void shutdown ();
} // interface TaxesOperations
