package Server;


/**
* Server/Taxes.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Taxes.idl
* Sunday, April 26, 2020 4:23:58 PM EDT
*/

public interface Taxes extends TaxesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Taxes
