package Server;


/**
* Server/TaxesHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Taxes.idl
* Sunday, April 26, 2020 4:23:58 PM EDT
*/

abstract public class TaxesHelper
{
  private static String  _id = "IDL:Server/Taxes:1.0";

  public static void insert (org.omg.CORBA.Any a, Server.Taxes that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Server.Taxes extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Server.TaxesHelper.id (), "Taxes");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Server.Taxes read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_TaxesStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Server.Taxes value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Server.Taxes narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Server.Taxes)
      return (Server.Taxes)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Server._TaxesStub stub = new Server._TaxesStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Server.Taxes unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Server.Taxes)
      return (Server.Taxes)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Server._TaxesStub stub = new Server._TaxesStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
